### ISSUE TITLE
ruby-rison fails to serialize/deserialize a simple hash with numeric keys

### ISSUE THREAD

**Issue by radfahrer** [tim/ruby-rison#1]
The following will throw an error:

    Rison.load Rison.dump( {1 => [2,3,4]})

The error is:

    Rison::ParseError: Invalid Rison input. Expected one of [T, F, N, NUMBER, STRING, ID, OBJECT, ARRAY] at line 1 char 1.

**Comment by tim** [comment]
@radfahrer Keys are either strings or id values, so that exception is correct behaviour for Rison.load. Rison.dump encoding the numeric keys is the bug, which I've fixed in d8f232f (available in v2.1.0).
